server:
  port: 8080

spring:
  application:
    name: franchise-api

  data:
    mongodb:
      uri: mongodb://localhost:27017/franchise_db

  # Configuración para continuar sin MongoDB si no está disponible
  autoconfigure:
    exclude: []

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.franchise: INFO
    org.springframework.data.mongodb: WARN
    root: WARN
