spring:
  # MongoDB configuration
  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true

  # Name of the application
  application:
    name: franchise-api

# Port Server
server:
  port: 8080

# Actuator (monitoring)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logs
logging:
  level:
    com.franchise: DEBUG
    org.springframework.data.mongodb: DEBUG
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
